image: google/dart:latest

before_script:
  - export PATH="$PATH":"~/.pub-cache/bin"
  - pub get --no-precompile

compile:
  script: dart2native ./bin/create.dart --output ./executables/setup_template
  artifacts:
    paths:
      - ./executables/setup_template
  only:
    changes:
      - bin/create.dart