image: google/dart:2.12

cache:
  paths:
    - .pub-cache/global_packages

before_script:
  - export PATH="$PATH":"~/.pub-cache/bin"
  - pub get --no-precompile

linux-compile:
  stage: build
  script:
    - dart compile exe ./bin/integrate.dart --output ./integrate

linux-release:
  stage: deploy
  script:
    - echo 'Release linux binary'
  release:
    tag_name: $CI_COMMIT_TAG
    description: 'Linux release $CI_COMMIT_TAG'
