name: service_integration_manager
description: Service integration tool to generate code automatically to integrate the backplane API with the i3-Marker microservices
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  validators2: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  http: ^0.13.1
  yaml: ^3.1.0
  petitparser: ^4.1.0


dev_dependencies:
  pedantic: ^1.11.0
