name: service_integration_manager
description: Service integration tool to generate code automatically to integrate the backplane API with the i3-Marker microservices
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.7.0
  recase: ^3.0.0
  validators: ^2.0.1
  http: ^0.12.2
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.2
